name: Build and deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: web/deadline
          username: ${{ secrets.username }}
          host: ${{ secrets.host }}
          privateKey: ${{ secrets.private_key }}
