name: Build and deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Npm install
        run: npm install
      - name: Build
        run: npm run-script build
        env:
          CI: true
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: web/deadline
          username: ${{ secrets.username }}
          host: ${{ secrets.host }}
          privateKey: ${{ secrets.private_key }}
